### PR TITLE
Update Bootcount for Hard/Soft Resets

### PR DESCRIPTION
**Pull request by yashika-batra**

### CODE REVIEW

**Review by thetazero — CHANGES_REQUESTED** [review]
Currently just doing +=1 instead of calling this function would have the same behavior. 

What are your thoughts on removing this function and doing it that way?

**Comment by yashika-batra** [comment]
> 

I tested this extensively, and doing += 1 doesn't wrap back around to 0 once it hits 255. Our bootcount variable has permanently been at 255 for some time now actually. I think we fixed this a while ago for the beepsat by editing the multiBitFlag class, but those edits aren't in the current library. I would also still rather have a function to do this for the sake of modularity / future usage.

**Comment by thetazero** [comment]
You're right, I got it backwards in my head. 

Honestly I would prefer that this counter doesn't wrap back around to 0, I feel like for the purposes of code 255 boots is roughly the same as any number bigger than 255, however 0 is very very different than 256 boots. 

What are your thoughts?

**Review by thetazero — APPROVED** [review]
I'm going to approve this and let you decide which behavior makes more sense to you.

**Comment by yashika-batra** [comment]
Closing this PR for now; I've implemented the reset_nvm function that Jacob described above and added it to the NVM test PR instead, as it felt more applicable there + was a dependency for that test.

**Pull request closed without merging**
