### PR TITLE
Handle bus and address changes for devices on different hardware versions

### PR DESCRIPTION
**Pull request by jbwillis**

### CODE REVIEW

**Comment by jbwillis** [comment]
Tested on flight unit 2 - works.

**Review by thetazero — APPROVED** [review]
Looks good.

I think just simple variables may be better than using a dictionary. I don't think it matters all that much though.

**Comment by thetazero** [comment]
This is a waste of memory that's my only concern*

**Review by thetazero — APPROVED** [review]
lint and it's good

**Pull request merged**
