### PR TITLE
State blinks

### PR DESCRIPTION
**Pull request by jbwillis**
There's probably a cleaner way to do this, but this has been super helpful in debugging deployment issues.

### CODE REVIEW

**Review by thetazero — CHANGES_REQUESTED** [review]
Probably don't want to blink the LED in safe mode, other than that this is good.

**Comment by jbwillis** [comment]
Tested on hardware.

**Comment by jbwillis** [comment]
Because Circuitpython has a habit of deleting/corrupting code files while connecting/disconnecting from a computer, I modified this to blink up to MAX_BLINKS times, or to blink indefinitely. Limiting to max_blinks allows us to reduce power consumption while also being able to observe the code is operating before integration.

**Review by thetazero — APPROVED** [review]
Have you made sure that blink_count gets reset, I'm not certain if it does.

**Comment by jbwillis** [comment]
It gets reset when the software gets reset (so this only runs MAX_BLINK
times immediately after boot). There might be a problem with it rolling
over to negatives though. I’ll add a check for that.

**Pull request merged**
